ebook_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  sku: RDI-SS-02
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
web_metadata:
  title:
    en: The Nectar of the Heart of Oral Instructions
    bo: ཞལ་གདམས་སྙིང་གི་བདུད་རྩི།
  collection:
    en: RDI Study Series–  Book 2
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༢
  author:
    en: Jamgon Kongtrul Lodro Thaye
    bo: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-02
  category:
    en: Pith Instructions
    bo: མན་ངག
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-02.epub
  description:
    en: ༄༅། །ན་མོ་གུ་རུ། ལས་དང་པོ་པ་ཡི་ངོ་བོ་སྐྱོང་ཚུལ་ལ། །འཛིན་པས་གཏན་ནས་མ་བསླད་མི་འབྱུང་ཞིང་།
      །དྲན་པ་ཁོ་ན་གནད་དུ་ཟབ་པས་ན། །དང་པོ་མི་ཡེངས་སྙམ་པའི་འཕེན་པ་བཏང་། །ཡེངས་ན་དེ་དབང་མི་བཏང་དམ་བཅའ་བཟུང་།
      །དྲན་པ་ཤུགས་འབྱུང་བྱུང་ན་དེ་རྒྱུན་བསྐྱང་། །རང་བབ་གསལ་སྟོང་ངང་དུ་གནས་པའི་ཚེ།
      །རང་ངོ་ཤེས་པས་བཅོས་མེད་ས་ལེར་བཞག །འཕྲོ་ན་རྟོག་པ་ཚུར་ལ་མི་འགུགས་པར། །མ་ཡེངས་བལྟས་པའི་གཉུག་མའི་ངང་དུ་གྲོལ།
      །ཚོགས་དྲུག་རྟོག་པ་ཇི་ལྟར་མང་ན་ཡང་། །སྤང་བླང་དགག་སྒྲུབ་མེད་པར་ལམ་དུ་ཁྱེར། །དྲན་ཤེས་ཡོད་ན་ཅིས་ཀྱང་འཆིང་མི་འགྱུར།
      །དྲན་རྫི་མེད་ན་ཡེངས་འཁྲུལ་དབང་དུ་འགྲོ། །ཡེངས་དང་མ་ཡེངས་ཙམ་གྱི་ཁྱད་པར་ལས། །བསྒོམ་རྒྱུའི་སེམས་ངོ་ཟེར་བ་ཅི་ཡང་མེད།
      །རྟོགས་པའི་རྐྱེན་ནི་སེམས་བསྐྱེད་མོས་གུས་དང་། །ཚོགས་གསོག་གང་འགྲུབ་བརྩོན་འགྲུས་བསྐྱེད་པ་དང་།
      །འཇིག་རྟེན་གསུམ་གྱི་མགོན་པོ་རྗེས་འཇུག་པ། །སྐལ་ལྡན་དཀོན་མཆོག་བསྟན་སྐྱོང་ཐུགས་བཞེད་ངོར།
      །སྒྲུབ་བརྒྱུད་རྟགས་འཛིན་གུ་ཎའི་མིང་གིས་བྲིས། །ཉམས་ལེན་མཐའ་རུ་ཕྱིན་པའི་བཀྲ་ཤིས་ཤོག
      །
    bo: ༄༅། །ན་མོ་གུ་རུ། ལས་དང་པོ་པ་ཡི་ངོ་བོ་སྐྱོང་ཚུལ་ལ། །འཛིན་པས་གཏན་ནས་མ་བསླད་མི་འབྱུང་ཞིང་།
      །དྲན་པ་ཁོ་ན་གནད་དུ་ཟབ་པས་ན། །དང་པོ་མི་ཡེངས་སྙམ་པའི་འཕེན་པ་བཏང་། །ཡེངས་ན་དེ་དབང་མི་བཏང་དམ་བཅའ་བཟུང་།
      །དྲན་པ་ཤུགས་འབྱུང་བྱུང་ན་དེ་རྒྱུན་བསྐྱང་། །རང་བབ་གསལ་སྟོང་ངང་དུ་གནས་པའི་ཚེ།
      །རང་ངོ་ཤེས་པས་བཅོས་མེད་ས་ལེར་བཞག །འཕྲོ་ན་རྟོག་པ་ཚུར་ལ་མི་འགུགས་པར། །མ་ཡེངས་བལྟས་པའི་གཉུག་མའི་ངང་དུ་གྲོལ།
      །ཚོགས་དྲུག་རྟོག་པ་ཇི་ལྟར་མང་ན་ཡང་། །སྤང་བླང་དགག་སྒྲུབ་མེད་པར་ལམ་དུ་ཁྱེར། །དྲན་ཤེས་ཡོད་ན་ཅིས་ཀྱང་འཆིང་མི་འགྱུར།
      །དྲན་རྫི་མེད་ན་ཡེངས་འཁྲུལ་དབང་དུ་འགྲོ། །ཡེངས་དང་མ་ཡེངས་ཙམ་གྱི་ཁྱད་པར་ལས། །བསྒོམ་རྒྱུའི་སེམས་ངོ་ཟེར་བ་ཅི་ཡང་མེད།
      །རྟོགས་པའི་རྐྱེན་ནི་སེམས་བསྐྱེད་མོས་གུས་དང་། །ཚོགས་གསོག་གང་འགྲུབ་བརྩོན་འགྲུས་བསྐྱེད་པ་དང་།
      །འཇིག་རྟེན་གསུམ་གྱི་མགོན་པོ་རྗེས་འཇུག་པ། །སྐལ་ལྡན་དཀོན་མཆོག་བསྟན་སྐྱོང་ཐུགས་བཞེད་ངོར།
      །སྒྲུབ་བརྒྱུད་རྟགས་འཛིན་གུ་ཎའི་མིང་གིས་བྲིས། །ཉམས་ལེན་མཐའ་རུ་ཕྱིན་པའི་བཀྲ་ཤིས་ཤོག
      །
